google_client_id: 33812809864-dr92pbet1sc9ph8vqum2bjl6s815km53.apps.googleusercontent.com
flask_secret_key: dev-secret-key
database:
  type: sqlite
  uri: synogym.sqlite
  sql_paths:
    - sqlite-schema.sql
    - sqlite-data.sql
