database:
  type: sqlite
  uri: synogym.sqlite
  sql_paths:
    - schema-sqlite.sql
server:
  port: 8080
  secret_key: dev-secret-key
  check_login: true
  static_folder: ../web
google_client_id: 33812809864-dr92pbet1sc9ph8vqum2bjl6s815km53.apps.googleusercontent.com
openai_api_key:
brainy_quotes_enabled: false
