CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL DEFAULT '',
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meanings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT NOT NULL,
    definition TEXT NOT NULL,
    pos TEXT NOT NULL,
    UNIQUE (query, definition, pos)
);

CREATE TABLE IF NOT EXISTS meaning_details (
    meaning_id INTEGER PRIMARY KEY,
    level TEXT NOT NULL,
    description TEXT NOT NULL,
    synonyms TEXT NOT NULL DEFAULT '[]',
    history TEXT NOT NULL,
    formations TEXT NOT NULL DEFAULT '[]',
    FOREIGN KEY (meaning_id) REFERENCES meanings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS examples (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meaning_id INTEGER NOT NULL,
    sentence TEXT NOT NULL,
    replacements TEXT NOT NULL DEFAULT '[]',
    FOREIGN KEY (meaning_id) REFERENCES meanings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookmarks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    meaning_id INTEGER NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (meaning_id) REFERENCES meanings(id) ON DELETE CASCADE,
    UNIQUE (user_id, meaning_id)
);

CREATE TABLE IF NOT EXISTS quotes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    author TEXT NOT NULL,
    url TEXT NOT NULL,
    UNIQUE (text, author, url)
);

CREATE INDEX IF NOT EXISTS idx_meanings_query ON meanings(query);
CREATE INDEX IF NOT EXISTS idx_examples_meaning_id ON examples(meaning_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_meaning_id ON bookmarks(meaning_id);
